<a href="https://colab.research.google.com/github/Noodle96/Topicos_Inteligencia_Artificial/blob/main/00_TorchIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip list

Package                           Version
--------------------------------- ------------------
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.1
anaconda-navigator                2.6.3
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data

## **PyTorch: a deep learning framework**
Pytorch is
<ul type="circle">
    <li>one of the most popular deep learning frameworks</li>
    <li>the framework used in many published deep learning papers</li>
    <li>intuitive and user-friendly</li>
    <li>has much in common with NumPy</li>
<ul/>

### **Importing PyTorch and related packages**
```python
import torch
```
PyTorch support
*   image data with ```torchvision ```
*   audio data with ```torchaudio ```
*   text data with ```torchtext ```

In [2]:
import torch
import numpy as np

In [3]:
lst = [ [1,2,3],
        [4,5,6]
    ]
print(lst)
print(type(lst))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


### **Tensors: the building blocks of networks in PyTorch**



> **Load from list**

In [4]:
lst_tensor = torch.tensor(lst)
print(lst_tensor)
print(type(lst_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


In [5]:
print(f"""{lst_tensor.shape}, {lst_tensor.dtype}, {lst_tensor.device}""")

torch.Size([2, 3]), torch.int64, cpu


> **Load from numpy**

In [6]:
np_list = np.array(lst)
np_tensor = torch.from_numpy(np_list)
print(np_tensor)
print(type(np_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


*   Tensor shape
*   Tensor data type
*   Tensor device

In [7]:
# np_tensor es ya un tensor
np_tensor.shape

torch.Size([2, 3])

In [8]:
np_tensor.dtype

torch.int64

In [9]:
np_tensor.device

device(type='cpu')

### **Getting started with tensor operations**

> **Compatibles shapes**

In [10]:
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[10,10],[20,20]])
print(a+b)

tensor([[11, 11],
        [22, 22]])


> **Incompatible shapes**

In [12]:
c = torch.tensor([[100,100],[200,200]])
d = torch.tensor([[1,2,3],[4,5,6]])
#c+d error by shape

Element-wise multiplication

In [14]:
e = torch.tensor([[1,2],[3,4]])
f = torch.tensor([[2,3],[5,6]])
e*f
print(type(e))
print(e*f)

<class 'torch.Tensor'>
tensor([[ 2,  6],
        [15, 24]])


In [15]:
class Coche:
  """Define las propiedades y comportamientos de un coche."""

  def __init__(self, marca, modelo, color):
    """Inicializa las propiedades del coche."""
    self.marca = marca
    self.modelo = modelo
    self.color = color

  def arrancar(self):
    """Simula el arranque del coche."""
    print(f"El {self.marca} {self.modelo} {self.color} está arrancando...")

  def acelerar(self, velocidad):
    """Simula la aceleración del coche."""
    print(f"El {self.marca} {self.modelo} {self.color} está acelerando a {velocidad} km/h")

  def frenar(self):
    """Simula el frenado del coche."""
    print(f"El {self.marca} {self.modelo} {self.color} está frenando...")

# Crea una instancia de la clase Coche
miCoche = Coche("Toyota", "Corolla", "azul")

# Llama a los métodos del coche
miCoche.arrancar()
miCoche.acelerar(80)
miCoche.frenar()
print(type(miCoche))


El Toyota Corolla azul está arrancando...
El Toyota Corolla azul está acelerando a 80 km/h
El Toyota Corolla azul está frenando...
<class '__main__.Coche'>


In [16]:
torch_zeros = torch.zeros(2,3)
torch_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch_ones = torch.ones(1,3)
torch_ones

tensor([[1., 1., 1.]])

In [18]:
torch_num = torch.full((3,4),7)
torch_num

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])

In [19]:
# Crea un tensor con valores aleatorios uniformes entre 0 y 1 de forma (2, 3)
tensor_aleatorio_uniforme = torch.rand(2, 3)
tensor_aleatorio_uniforme

tensor([[0.4037, 0.7419, 0.1120],
        [0.6974, 0.0927, 0.1904]])

In [20]:
# Crea un tensor con valores aleatorios normales (distribución gaussiana) de forma (2, 3)
tensor_aleatorio_normal = torch.randn(2, 3)
tensor_aleatorio_normal

tensor([[ 1.0633, -0.1193, -0.0746],
        [ 1.7647,  2.5592,  1.6103]])

____
____

## 🔹 1) Semillas y reproducibilidad

Para asegurar *reproducibilidad* en los experimentos, fijamos semillas aleatorias.  
Esto hace que las inicializaciones y valores aleatorios sean consistentes entre ejecuciones.  

- **random.seed()**: controla aleatoriedad de Python.  
- **np.random.seed()**: controla aleatoriedad de NumPy.  
- **torch.manual_seed()**: controla aleatoriedad en PyTorch (CPU).  
- **torch.cuda.manual_seed_all()**: controla aleatoriedad en PyTorch (GPU, si está disponible).  

> ⚠️ Nota: Activar determinismo en `cudnn` puede reducir el rendimiento.

In [21]:
import torch, random, numpy as np

SEED = 1337
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# Opcional: más determinismo (puede reducir rendimiento)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


## 🔹 2) `device` y `dtype` (CPU/GPU y tipos de dato)

Cada tensor en PyTorch tiene dos atributos clave:

- **device** → dónde se almacena: `cpu` o `cuda` (GPU).  
- **dtype** → tipo de dato: `torch.float32`, `torch.int64`, etc.  

En entrenamiento con redes neuronales:  
- Usamos casi siempre **float32**.  
- Si hay GPU, mover tensores a `cuda` acelera los cálculos.  


In [29]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Usando:", device)

x = torch.randn(2, 3, dtype=torch.float32, device=device)
print("dtype:", x.dtype, "| device:", x.device)

# Mover tensor explícitamente
x_cpu = x.to('cpu')
x_gpu = x.to(device)
print(x_cpu)
print(x_gpu)


Usando: cuda
dtype: torch.float32 | device: cuda:0
tensor([[-0.4470,  0.8750,  0.6787],
        [ 0.4578, -0.8858,  0.4472]])
tensor([[-0.4470,  0.8750,  0.6787],
        [ 0.4578, -0.8858,  0.4472]], device='cuda:0')


## 🔹 3) `unsqueeze` y `squeeze`

Estas operaciones permiten **añadir o quitar dimensiones** de tamaño 1:

- `unsqueeze(dim)` → inserta una dimensión de tamaño 1 en la posición `dim`.  
- `squeeze(dim)` → elimina una dimensión de tamaño 1 (si existe).  

👉 Muy útil al preparar *batches*, canales de imágenes, o secuencias.  


In [34]:
t = torch.tensor([10, 20, 30])   # [3]
print("t shape:", t.shape)

t_unsq0 = t.unsqueeze(0)         # [1,3]
print("t_unsq0 shape:", t_unsq0.shape)
print("t_unsq0:", t_unsq0)

t_unsq1 = t.unsqueeze(1)         # [3,1]
print("t_unsq1 shape:", t_unsq1.shape)
print("t_unsq1:", t_unsq1)


t_sq = t_unsq1.squeeze()         # [3]
print("t_sq shape:", t_sq.shape)
print("t_sq:", t_sq)

print("t:", t.shape, "| unsqueeze(0):", t_unsq0.shape, "| unsqueeze(1):", t_unsq1.shape, "| squeeze:", t_sq.shape)


t shape: torch.Size([3])
t_unsq0 shape: torch.Size([1, 3])
t_unsq0: tensor([[10, 20, 30]])
t_unsq1 shape: torch.Size([3, 1])
t_unsq1: tensor([[10],
        [20],
        [30]])
t_sq shape: torch.Size([3])
t_sq: tensor([10, 20, 30])
t: torch.Size([3]) | unsqueeze(0): torch.Size([1, 3]) | unsqueeze(1): torch.Size([3, 1]) | squeeze: torch.Size([3])


In [38]:
t_test = torch.tensor([[1,2,3],[4,5,6]])  # [2,3]
print("t_test shape:", t_test.shape)
print("t_test: ", t_test)

t_test_unsq0 = t_test.unsqueeze(0)      # [1,2,3]
print("\n\nt_test_unsq0 shape:", t_test_unsq0.shape)
print("t_test_unsq0: ", t_test_unsq0)

t_test_sq1 = t_test_unsq0.squeeze(0)   # [2,3]
print("\n\nt_test_sq1 shape:", t_test_sq1.shape)
print("t_test_sq1: ", t_test_sq1)


t_test shape: torch.Size([2, 3])
t_test:  tensor([[1, 2, 3],
        [4, 5, 6]])


t_test_unsq0 shape: torch.Size([1, 2, 3])
t_test_unsq0:  tensor([[[1, 2, 3],
         [4, 5, 6]]])


t_test_sq1 shape: torch.Size([2, 3])
t_test_sq1:  tensor([[1, 2, 3],
        [4, 5, 6]])


## 🔹 4) `reshape` vs `view`

Ambas permiten cambiar la forma (*shape*) de un tensor:

- **`view()`** → más eficiente, pero requiere que el tensor sea **contiguo** en memoria.  
- **`reshape()`** → intenta usar `view`, y si no puede, crea una copia.  

💡 Si un tensor fue transpuesto (`transpose`/`permute`), usar `contiguous()` antes de `view()`.  


In [41]:
a = torch.arange(12)            # [12]
print("a: ", a)
b = a.view(3, 4)                # [3,4] (contiguo)
print("b: ", b)
c = b.t()                       # [4,3] (no contiguo)
print("c: ", c)
print("c.contiguous?", c.is_contiguous())

# Para usar view:
c2 = c.contiguous().view(2, 6)
print("c2.shape:", c2.shape)
print("c2:", c2)

# reshape funciona aunque no sea contiguo
r2 = c.reshape(2, 6)

print("c2.shape:", c2.shape, "| r2.shape:", r2.shape)


a:  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
b:  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
c:  tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
c.contiguous? False
c2.shape: torch.Size([2, 6])
c2: tensor([[ 0,  4,  8,  1,  5,  9],
        [ 2,  6, 10,  3,  7, 11]])
c2.shape: torch.Size([2, 6]) | r2.shape: torch.Size([2, 6])


## 🔹 5) `transpose` y `permute`

Para **reordenar ejes** de un tensor:

- `transpose(dim0, dim1)` → intercambia dos dimensiones.  
- `permute(dims)` → reordena las dimensiones arbitrariamente.  

> ⚠️ Estos resultados suelen no ser contiguos en memoria.  


In [43]:
x = torch.randn(2, 3, 4)        # [B=2, C=3, T=4]
print("x shape:", x.shape)
print("x:", x)

x_t = x.transpose(1, 2)         # [2,4,3]
x_p = x.permute(0, 2, 1)        # [2,4,3]

print("x:", x.shape, "| transpose:", x_t.shape, "| permute:", x_p.shape)


x shape: torch.Size([2, 3, 4])
x: tensor([[[ 1.1490,  0.1812, -0.0920,  1.5828],
         [ 0.1526,  0.3843,  1.3091,  0.4645],
         [-0.8345,  0.5978, -0.0514, -0.0646]],

        [[-0.4970,  0.4658, -0.2573, -1.0673],
         [ 2.0089, -0.5370,  0.2228,  0.6971],
         [-1.4267,  0.9059,  0.1446,  0.2280]]])
x: torch.Size([2, 3, 4]) | transpose: torch.Size([2, 4, 3]) | permute: torch.Size([2, 4, 3])
