<a href="https://colab.research.google.com/github/Noodle96/Topicos_Inteligencia_Artificial/blob/main/00_TorchIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#!pip list

## **PyTorch: a deep learning framework**
Pytorch is
<ul type="circle">
    <li>one of the most popular deep learning frameworks</li>
    <li>the framework used in many published deep learning papers</li>
    <li>intuitive and user-friendly</li>
    <li>has much in common with NumPy</li>
<ul/>

### **Importing PyTorch and related packages**
```python
import torch
```
PyTorch support
*   image data with ```torchvision ```
*   audio data with ```torchaudio ```
*   text data with ```torchtext ```

In [1]:
import torch
import numpy as np

In [2]:
lst = [ [1,2,3],
        [4,5,6]
    ]
print(lst)
print(type(lst))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


### **Tensors: the building blocks of networks in PyTorch**



> **Load from list**

In [7]:
lst_tensor = torch.tensor(lst)
print(lst_tensor)
print(type(lst_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


In [9]:
print(f"""{lst_tensor.shape}, {lst_tensor.dtype}, {lst_tensor.device}""")

torch.Size([2, 3]), torch.int64, cpu


> **Load from numpy**

In [10]:
np_list = np.array(lst)
np_tensor = torch.from_numpy(np_list)
print(np_tensor)
print(type(np_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


*   Tensor shape
*   Tensor data type
*   Tensor device

In [ ]:
# np_tensor es ya un tensor
np_tensor.shape

torch.Size([2, 3])

In [ ]:
np_tensor.dtype

torch.int64

In [ ]:
np_tensor.device

device(type='cpu')

### **Getting started with tensor operations**

> **Compatibles shapes**

In [ ]:
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[10,10],[20,20]])
print(a+b)

tensor([[11, 11],
        [22, 22]])


> **Incompatible shapes**

In [ ]:
c = torch.tensor([[100,100],[200,200]])
d = torch.tensor([[1,2,3],[4,5,6]])
#c+d

Element-wise multiplication

In [ ]:
e = torch.tensor([[1,2],[3,4]])
f = torch.tensor([[2,3],[5,6]])
e*f
print(type(e))

<class 'torch.Tensor'>


In [ ]:
class Coche:
  """Define las propiedades y comportamientos de un coche."""

  def __init__(self, marca, modelo, color):
    """Inicializa las propiedades del coche."""
    self.marca = marca
    self.modelo = modelo
    self.color = color

  def arrancar(self):
    """Simula el arranque del coche."""
    print(f"El {self.marca} {self.modelo} {self.color} está arrancando...")

  def acelerar(self, velocidad):
    """Simula la aceleración del coche."""
    print(f"El {self.marca} {self.modelo} {self.color} está acelerando a {velocidad} km/h")

  def frenar(self):
    """Simula el frenado del coche."""
    print(f"El {self.marca} {self.modelo} {self.color} está frenando...")

# Crea una instancia de la clase Coche
miCoche = Coche("Toyota", "Corolla", "azul")

# Llama a los métodos del coche
miCoche.arrancar()
miCoche.acelerar(80)
miCoche.frenar()
print(type(miCoche))


El Toyota Corolla azul está arrancando...
El Toyota Corolla azul está acelerando a 80 km/h
El Toyota Corolla azul está frenando...
<class '__main__.Coche'>


In [ ]:
torch_zeros = torch.zeros(2,3)
torch_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch_ones = torch.ones(1,3)
torch_ones

tensor([[1., 1., 1.]])

In [ ]:
torch_num = torch.full((3,4),7)
torch_num

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])

In [ ]:
# Crea un tensor con valores aleatorios uniformes entre 0 y 1 de forma (2, 3)
tensor_aleatorio_uniforme = torch.rand(2, 3)
tensor_aleatorio_uniforme

tensor([[0.8761, 0.0361, 0.6827],
        [0.7248, 0.0904, 0.2620]])

In [ ]:
# Crea un tensor con valores aleatorios normales (distribución gaussiana) de forma (2, 3)
tensor_aleatorio_normal = torch.randn(2, 3)
tensor_aleatorio_normal

tensor([[ 0.2389, -0.3523, -2.9853],
        [ 0.4663, -1.3307, -0.6641]])