<a href="https://colab.research.google.com/github/Noodle96/Topicos_Inteligencia_Artificial/blob/main/03_RunningForwardPass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Running a forward pass**

### **Binary classification: forward pass**

In [37]:
import torch
import torch.nn as nn

In [38]:
# Create input data of shape 5x6
input_data = torch.tensor(
    [[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [-0.9155, -0.0475, -1.3645,0.6336, -1.9520, -0.3398],
    [ 0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
    [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
    [-0.7413, 1.7920, -0.0883, -0.6685,0.4745, -0.4245]]
)
print(input_data.shape)
print(input_data.dtype)

torch.Size([5, 6])
torch.float32


El Modelo ```modelo01``` gráficamente lo podemos ver asi:

<div style="display: flex; flex-direction: row;justify-content: space-between;">
  <img src="https://github.com/Noodle96/Topicos_Inteligencia_Artificial/blob/main/assets/img/03_binaryClasification.png?raw=true" width="90%">
</div>

In [39]:
# Creamos un modelo de clasificacion binaria
model01 = torch.nn.Sequential(
    nn.Linear(6, 4), # Primera capa lineal
    nn.Linear(4, 1), # Segunda capa lineal
    nn.Sigmoid() # a la salida se le aplica la funcion sigmoidea
)
print(model01)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
  (2): Sigmoid()
)


Sea:
*   A : Matriz **Input data**
*   B: Transpuesta matriz **weight** between input layer and hidden layer
*   b: matriz **bias** between input layer and hidden layer
*   C: Matriz input to hidden layer

Forward entre A y B
$$
  \left(\underset{(5 \times 6)}{A} \times \underset{(6 \times 4)}{B} \right) + \underset{(5 \times 4)}{b}   \ = \underset{(5\times 4)}{C}
$$

*   D: Transpuesta matriz **weight** between hidden layer and output
*   d: matriz **bias** between **input layer** and **hidden layer**
*   E: preactivation

Forward entre C y D

$$
  \left(\underset{(5 \times 4)}{C} \times \underset{(4 \times 1)}{D}\right) + \underset{(5 \times 1)}{b}   \ = \underset{(5\times 1)}{E}
$$

Finalmente the preactivation queda de la forma:

$$
    \underset{(5\times 1)}{E}
$$




In [40]:
for e in model01.children():
    # con este of evitamos entrar a nn.Sigmoid()
    if isinstance(e, nn.Linear):
        print(e.weight.shape)
        print(e.weight)
        print(e.bias.shape)
        print(e.bias)

torch.Size([4, 6])
Parameter containing:
tensor([[ 0.2631, -0.2695,  0.4025, -0.2255, -0.0715,  0.1756],
        [ 0.0626,  0.1894, -0.1724,  0.2952,  0.2952, -0.1753],
        [ 0.0903, -0.1975,  0.3600, -0.3122,  0.2341,  0.0534],
        [-0.0289, -0.3240,  0.0518,  0.2426,  0.0342,  0.1362]],
       requires_grad=True)
torch.Size([4])
Parameter containing:
tensor([ 0.0783,  0.0537, -0.2683, -0.3274], requires_grad=True)
torch.Size([1, 4])
Parameter containing:
tensor([[ 0.2161, -0.4950,  0.4738,  0.4519]], requires_grad=True)
torch.Size([1])
Parameter containing:
tensor([-0.1337], requires_grad=True)


In [41]:
# Pasar el dato de entrada atraves del modelo
output01 = model01(input_data)
print(output01)
output01.shape

tensor([[0.4512],
        [0.2494],
        [0.1946],
        [0.3021],
        [0.2414]], grad_fn=<SigmoidBackward0>)


torch.Size([5, 1])

### **Multi-class classification: forward passpass**

El ```modelo02``` lo podemos graficamente ver asi

<div style="display: flex; flex-direction: row;justify-content: space-between;">
  <img src="https://github.com/Noodle96/Topicos_Inteligencia_Artificial/blob/main/assets/img/03_MultiClassClasification.png?raw=true" width="90%">
</div>

In [42]:
# Specify model has three classes
n_classes = 3

In [43]:
# Create multiclass classification model
model02 = nn.Sequential(
    nn.Linear(6, 4), # First linear layer
    nn.Linear(4, n_classes), # Second linear layer
    nn.Softmax(dim=-1) # Softmax activation
)
print(model02)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
  (2): Softmax(dim=-1)
)


Hacer el mismo procedimiento que la clasificacion binaria

In [47]:
# Pass input data through model
output02 = model02(input_data)
print(output02)
print(output02.shape)

tensor([[0.1500, 0.3520, 0.4980],
        [0.3877, 0.1819, 0.4303],
        [0.2529, 0.2363, 0.5107],
        [0.3229, 0.2300, 0.4471],
        [0.2367, 0.2554, 0.5079]], grad_fn=<SoftmaxBackward0>)
torch.Size([5, 3])


### **Regression: forward pass**

El ```modelo03``` lo podemos graficamente ver asi

<div style="display: flex; flex-direction: row;justify-content: space-between;">
  <img src="https://github.com/Noodle96/Topicos_Inteligencia_Artificial/blob/main/assets/img/03_regresion.png?raw=true" width="50%">
</div>

In [45]:
# creacion del modelo 03
model03 = nn.Sequential(
    nn.Linear(6, 4), # First linear layer
    nn.Linear(4, 1), # Second linear layer
)
print(model03 )

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [46]:
output03 = model03(input_data)
print(output03)
output03.shape

tensor([[-0.1878],
        [-0.1270],
        [-0.2307],
        [-0.0499],
        [-0.1177]], grad_fn=<AddmmBackward0>)


torch.Size([5, 1])