<a href="https://colab.research.google.com/github/Noodle96/Topicos_Inteligencia_Artificial/blob/main/introduccion_deep_learning_with_pytorch/04_using_loss_functions_to_assess_model_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Why do we need a loss function?**

*   Gives feedback to model during training
*   Takes in model prediction $\hat y$ and ground truth y
*   Outputs a float

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import numpy as np

## **One-hot encoding  concepts**



*   loss = $F(y, \hat y)$
*   $y$ es un solo entero (clase label)
*   $\hat y$ es un tensor(output de softmax) de dimension $n$ .
*   **Entonces, como comparamos un entero(class) con un tensor(tensor dimension n)?**


In [2]:
one_hot_numpy = np.array([1, 0, 0])
one_hot_tensor  = torch.tensor([1, 0, 0])
print(one_hot_numpy,one_hot_numpy.shape, one_hot_numpy.dtype,type(one_hot_numpy))
print(one_hot_tensor, one_hot_tensor.shape, one_hot_tensor.dtype, type(one_hot_tensor))
print(one_hot_tensor)

[1 0 0] (3,) int64 <class 'numpy.ndarray'>
tensor([1, 0, 0]) torch.Size([3]) torch.int64 <class 'torch.Tensor'>
tensor([1, 0, 0])


## **Transforming labels with one-hot encoding**

In [3]:
import torch.nn.functional as F

In [4]:
clase1 = F.one_hot(torch.tensor(0),num_classes=3)
print(clase1)

tensor([1, 0, 0])


In [5]:
clase2 = F.one_hot(torch.tensor(1),num_classes=3)
print(clase2)

tensor([0, 1, 0])


In [6]:
clase3 = F.one_hot(torch.tensor(2),num_classes=3)
print(clase3)

tensor([0, 0, 1])


In [7]:
claseTest = F.one_hot(torch.tensor([0,1,2]),num_classes=3)
print(claseTest)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])


In [8]:
claseError = F.one_hot(torch.tensor(4),num_classes=3)
print(claseError)

RuntimeError: Class values must be smaller than num_classes.

## **Cross entropy loss in PyTorch**

In [ ]:
from torch.nn import CrossEntropyLoss

In [ ]:
scores = torch.tensor([[-0.1211, 0.1059]])
one_hot_target = torch.tensor([[1, 0]])
print(scores)
print(one_hot_target)

In [ ]:
criterion = CrossEntropyLoss()
loss = criterion(scores.double(), one_hot_target.double())
print(loss)