<a href="https://colab.research.google.com/github/Noodle96/Topicos_Inteligencia_Artificial/blob/main/03_RunningForwardPass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Running a forward pass**

### **Binary classification: forward pass**

In [17]:
import torch
import torch.nn as nn

In [18]:
# Create input data of shape 5x6
input_data = torch.tensor(
    [[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [-0.9155, -0.0475, -1.3645,0.6336, -1.9520, -0.3398],
    [ 0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
    [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
    [-0.7413, 1.7920, -0.0883, -0.6685,0.4745, -0.4245]]
)
print(input_data.shape)
print(input_data.dtype)

torch.Size([5, 6])
torch.float32


El Modelo ```modelo01``` gráficamente lo podemos ver asi:

<div style="display: flex; flex-direction: row;justify-content: space-between;">
  <img src="https://github.com/Noodle96/Topicos_Inteligencia_Artificial/blob/main/assets/img/03_binaryClasification.png?raw=true" width="90%">
</div>

In [19]:
# Creamos un modelo de clasificacion binaria
model01 = torch.nn.Sequential(
    nn.Linear(6, 4), # Primera capa lineal
    nn.Linear(4, 1), # Segunda capa lineal
    nn.Sigmoid() # a la salida se le aplica la funcion sigmoidea
)
print(model01)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
  (2): Sigmoid()
)


In [20]:
# Pasar el dato de entrada atraves del modelo
output01 = model01(input_data)
print(output01)
output01.shape

tensor([[0.4963],
        [0.4648],
        [0.5222],
        [0.4129],
        [0.4816]], grad_fn=<SigmoidBackward0>)


torch.Size([5, 1])

### **Multi-class classification: forward passpass**

El ```modelo02``` lo podemos graficamente ver asi

<div style="display: flex; flex-direction: row;justify-content: space-between;">
  <img src="https://github.com/Noodle96/Topicos_Inteligencia_Artificial/blob/main/assets/img/03_MultiClassClasification.png?raw=true" width="90%">
</div>

In [25]:
# Specify model has three classes
n_classes = 3

In [33]:
# Create multiclass classification model
model02 = nn.Sequential(
    nn.Linear(6, 4), # First linear layer
    nn.Linear(4, n_classes), # Second linear layer
    nn.Softmax(dim=-1) # Softmax activation
)
print(model02)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
  (2): Softmax(dim=-1)
)


In [28]:
# Pass input data through model
output02 = model02(input_data)
print(output02)
print(output02.shape)

tensor([[0.2120, 0.5582, 0.2297],
        [0.2762, 0.3950, 0.3288],
        [0.1614, 0.5460, 0.2926],
        [0.3783, 0.3931, 0.2286],
        [0.1997, 0.5655, 0.2348]], grad_fn=<SoftmaxBackward0>)
torch.Size([5, 3])


### **Regression: forward pass**

El ```modelo03``` lo podemos graficamente ver asi

<div style="display: flex; flex-direction: row;justify-content: space-between;">
  <img src="https://github.com/Noodle96/Topicos_Inteligencia_Artificial/blob/main/assets/img/03_regresion.png?raw=true" width="50%">
</div>

In [31]:
# creacion del modelo 03
model03 = nn.Sequential(
    nn.Linear(6, 4), # First linear layer
    nn.Linear(4, 1), # Second linear layer
)
print(model03 )

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [32]:
output03 = model03(input_data)
print(output03)
output03.shape

tensor([[0.4254],
        [0.0149],
        [0.1207],
        [0.0340],
        [0.2174]], grad_fn=<AddmmBackward0>)


torch.Size([5, 1])