<a href="https://colab.research.google.com/github/Noodle96/Topicos_Inteligencia_Artificial/blob/main/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip list

## **PyTorch: a deep learning framework**
Pytorch is
<ul type="circle">
    <li>one of the most popular deep learning frameworks</li>
    <li>the framework used in many published deep learning papers</li>
    <li>intuitive and user-friendly</li>
    <li>has much in common with NumPy</li>
<ul/>

### **Importing PyTorch and related packages**
```python
import torch
```
PyTorch support
*   image data with ```torchvision ```
*   audio data with ```torchaudio ```
*   text data with ```torchtext ```

In [2]:
import torch
import numpy as np

In [3]:
lst = [ [1,2,3],
        [4,5,6]
    ]
print(lst)
print(type(lst))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


### **Tensors: the building blocks of networks in PyTorch**



> **Load from list**

In [4]:
lst_tensor = torch.tensor(lst)
print(lst_tensor)
print(type(lst_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


In [5]:
print(f"""{lst_tensor.shape}, {lst_tensor.dtype}, {lst_tensor.device}""")

torch.Size([2, 3]), torch.int64, cpu


> **Load from numpy**

In [6]:
np_list = np.array(lst)
np_tensor = torch.from_numpy(np_list)
print(np_tensor)
print(type(np_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


*   Tensor shape
*   Tensor data type
*   Tensor device

In [7]:
# np_tensor es ya un tensor
np_tensor.shape

torch.Size([2, 3])

In [8]:
np_tensor.dtype

torch.int64

In [9]:
np_tensor.device

device(type='cpu')

### **Getting started with tensor operations**

> **Compatibles shapes**

In [10]:
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[10,10],[20,20]])
print(a+b)

tensor([[11, 11],
        [22, 22]])


> **Incompatible shapes**

In [11]:
c = torch.tensor([[100,100],[200,200]])
d = torch.tensor([[1,2,3],[4,5,6]])
#c+d

Element-wise multiplication

In [12]:
e = torch.tensor([[1,2],[3,4]])
f = torch.tensor([[2,3],[5,6]])
e*f

tensor([[ 2,  6],
        [15, 24]])